---

- set_fact:
    font_directory: "{{ 'Library/Fonts' if ansible_os_family == 'Darwin' else '.local/share/fonts' }}"

- name: install fontconfig
  become: ansible_os_family == "Debian"
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - fontconfig
  tags:
    - packages
    - powerline-fonts

- name: download powerline-fonts repository from github
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: /tmp/powerline-fonts
  tags:
    - powerline-fonts

- name: ensure all users have a local fonts directory
  file:
    # First tilde expands to home dir via expanduser. Others tildes are for concatenation.
    dest: "{{ '~' ~ item.user ~ '/' ~ font_directory | expanduser }}"
    state: directory
    owner: "{{ item.user }}"
    # group: "{{ item.user }}"
  with_items: "{{ all_users }}"
  ignore_errors: yes
  tags:
    - powerline-fonts

- name: copy fonts
  command: cp -r /tmp/powerline-fonts/{{ item[1] }} {{ '~' ~ item[0].user ~ '/' ~ font_directory | expanduser }}
  with_nested:
   - "{{ all_users }}"
   - "{{ all_fonts }}"
  tags:
    - powerline-fonts

- name: set fonts directory ownership
  file:
    dest: "{{ '~' ~ item[0].user ~ '/' ~ font_directory ~ '/' ~ item[1] | expanduser }}"
    state: directory
    owner: "{{ item[0].user }}"
    # group: "{{ item[0].user }}"
  with_nested:
   - "{{ all_users }}"
   - "{{ all_fonts }}"
  ignore_errors: yes
  tags:
    - powerline-fonts

- name: reset font cache
  command: fc-cache -f {{ '~' ~ item.user ~ '/' ~ font_directory | expanduser }}
  with_items: "{{ all_users }}"
